version: '3'

volumes:
  pgdata:

services:
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:12-alpine
    volumes:
      - pgdata:/data:delegated
    environment:
      PGDATA: /data
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
